### ISSUE TITLE
DropFrame Timecode Adding Frames to minutes divisible by 10?

### ISSUE THREAD

**Issue by jsciame** [guerilla-di/timecode#8]
I pulled the latest gem from github. I was testing out drop-frame support for a project. When I create a new Timecode object, it seems to be adding 2 frames to timecode minutes that ARE divisible by 10. I would have expected the dropping of frames 00, 01 only on minutes not divisible by 10.  

```
load '~/timecode-2.2.1/lib/timecode.rb'

item = Timecode.at(01, 10, 00, 00, with_fps=29.97, drop_frame=true)
puts item
puts item.to_i
```

```
/Users/jsciame/.rbenv/versions/2.2.2/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/jsciame/RubymineProjects/Files/timecode_test.rb
01:10:00;02
125876
```

**Comment by julik** [comment]
@pcipriano can you take this? I am a happy camper in PAL land so I might be underqualified to cope :-)

**Comment by jsciame** [comment]
@pcipriano Any update on this ticket?

**Comment by julik** [comment]
@jsciame I think @pcipriano disappeared into the ether, which is fair enough. I am willing to help you with the issue if you explain it in very minute detail. Can you put in more snippets that would demonstrate the desired outcomes vs. actual outcomes as it stands now? Then I might be able to cook up something.

**Comment by pcipriano** [comment]
Sorry, at the moment my time is really limited. I don't know when I can look at this. Surely is a quick fix.

**Comment by julik** [comment]
@pcipriano it was not a call for an emergency, do not worry :-) I just want to help but missing the expertise. It is an opensource project and you are not expected to be "on call" for all the features you implemented, of course not. Take your time ❤️

**Comment by jsciame** [comment]
Sorry, @pcipriano @julik. I accidentally closed the ticket while looking to see if it was updated so I had to reopened. Here is what I'm seeing. I give it 1 hour at 29.97 drop frame. It returns me an incorrect frames value. I believe 17892 is the correct frames in a drop frame hour. The other odd thing is if I give 17894 frames back, it returns me a different timecode value than I gave it. 

`new = Timecode.new("01:00:00;00", fps=29.97)
timecode = Timecode.new(total = new, fps = 29.97, drop_frame = true)

puts new.to_i
puts frames.to_s`

Returns
new - 107894
timecode - 01:00:00;02

**Comment by jsciame** [comment]
@julik Here is code I wrote that takes timecode and converts it to frames in drop frame.

`def tctoframes(timecode, framerate)
  hours, minutes, seconds, frames = timecode.split(/[;,:]/).map!(&:to_i)
  totalFrames = (hours * 60 * 60 * framerate) + (minutes * 60 * framerate) + (seconds * framerate) + frames
  totalMinutes = (hours * 60) + minutes
  frames_to_drop = (0...totalMinutes).to_a.map { |i| i if i % 10 != 0 }.compact!.size * 2
  totalFrames = totalFrames - frames_to_drop
  return totalFrames
end
`

**Comment by eliskah** [comment]
I was also experimenting with this gem, works great for my use case, thanks for that!

I noticed this confusing behaviour that maybe causes pain for @jsciame:

````ruby
# One hour with milliseconds, please note there is `.`, not a `;` semicolon: 
tc = Timecode.new("01:00:00.000", 29.97, true)
# => ##<Timecode:01:00:00:00 (108000F@29.97)>
"%02d:%02d:%02d;%d" % [tc.hours, tc.minutes, tc.seconds, tc.frames]
# => "01:00:00;0" (correct timecode with frames)
tc.to_i
# => 108000 (incorrect, number of frames should be 107892)
````

What I also use is this `from_seconds` class method, which looks like it is free from this:

````ruby
tc = Timecode.from_seconds(3600, 29.97, true)
# => #<Timecode:01:00:00:00 (107892F@29.97)>
"%02d:%02d:%02d;%d" % [tc.hours, tc.minutes, tc.seconds, tc.frames]
# =>  "01:00:00;0" (exactly as I want it)
tc.to_i
# => 107892 (correct)
````

It seems to me that the problematic part is when the object is [assigned the `@total`](https://github.com/guerilla-di/timecode/blob/master/lib/timecode.rb#L103) here.

**Comment by eliskah** [comment]
@julik I originally came here because I can't understand this [notice in comments](https://github.com/guerilla-di/timecode/blob/master/lib/timecode.rb#L3-L4):

> An additional perk might be to save the dropframeness, but we avoid that at this point 

Could you please explain it? Thank you 🙂

**Comment by julik** [comment]
@eliskah the reason the comment is there is I have added it right at the gem's inception, over 9 years ago (no joke!). @pcipriano has added dropframe support but did not remove that comment, so that's what got you confused :-) I have now removed the comment.

**Comment by eliskah** [comment]
@julik wow, that's amazing! Thank you for the quick response.

**Comment by He-Fr** [comment]
@julik @pcipriano Any update on this ticket ?
The problem is still present in 2.2.2 :
Timecode.new("01:00:00;00",29.97)
<Timecode:01:00:00:02 (107894F@29.97)>

**Comment by julik** [comment]
Ok, I think I need to figure out what's going on with this drop - frame stuff once and for all. But I won't get at this until the end of the week at the earliest. @eliskah @He-Fr can you point me to a _very_ good document explaining the following (because this is what I don't understand with drop-frame timecode):

** At framerate R, given framecount F from the start of the program (or start of tape), how to compute the timecode T? **

The timecode gem uses framecount internally. Can there be a possibility that it's actually impossible to derive a drop-frame timecode from that framecount, and there is some other "tricky" value that has to be carried along with the timecode object somehow?

**Comment by eliskah** [comment]
@julik will try to review tomorrow or Friday

**Comment by eliskah** [comment]
@julik all I know about dropping frames comes from this article: http://andrewduncan.net/timecodes/

>** At framerate R, given framecount F from the start of the program (or start of tape), how to compute the timecode T? **

At the very end, there are formulas for the `29.97` rate, I think for `59.94` we just drop 4 frames instead of two and the logic is unchanged. For `23.976` I have no clue.

However, I am not sure the internally used number of frames is correct in the example @He-Fr shared, so the result might be wrong even with correct formula.

`frameNumber = seconds * 29.97` and so one hour should have 107 892 frames: `60*60*29.97 = 107892`

```ruby
t = Timecode.new("01:00:00;00",29.97)
# => #<Timecode:01:00:00:02 (107894F@29.97)>
t.to_i
# => 107894  # two more frames
```

I tried changing locally a condition [here](https://github.com/guerilla-di/timecode/blob/master/lib/timecode.rb#L212 ) to:

```ruby
if drop_frame && secs == 0 && (mins % 10 > 0) && (frames < comp.drop_count)
```

... as `(mins % 10)` is always resolved to true and did not have any effect.

After that change I was getting these frame counts as expected:

```ruby
t = Timecode.new("00:10:00;00",29.97, true)
# => #<Timecode:00:10:00:00 (17982F@29.97)>
t.to_i
# => 17982
```

Also the frame counts for minutes where dropping happens is calculated correctly:

```ruby
t = Timecode.new("00:01:00;02", 29.97, true)
=> #<Timecode:00:01:00:02 (1800F@29.97)>
t.to_i
# => 1800
```

Is that helpful?

**Comment by ValZapod** [comment]
> For `23.976` I have no clue.

That is not supported by SMPTE. Anyway, drop frame timecode accumulates 1 extra frame after 9 hours 15 minutes, so what is the point of it.

**Comment by eliskah** [comment]
Haha, that's funny, I don't remember anything about dropping frames anymore 😄 Happy to hear the comment helped you.
